from transformers import pipeline
import scipy
from llamaapi import LlamaAPI
# also import GPT-4 from OpenAI
from openai import OpenAI


TRANSCRIPTION_FILE_LIST = ["output.txt"]

def generate_music_description(transcription, model="Llama"):
    """_summary_

    Args:
        transcription (string): the diariesed transcription of the audio file which we extracted from a txt file.

    Returns:
        string: the music description generated by GPT-4/Llama (TBD)
    """
    pass


def description_to_audio(description, output_name):
    """

    Args:
        description (string): the music description generated by GPT-4/Llama (TBD)
        output_name (string): the name of the audio file to be written
    
    Returns:
        None: writes the audio file to the output_name
    """
    synthesiser = pipeline("text-to-audio", "facebook/musicgen-small")
    music = synthesiser(output_name, forward_params={"do_sample": True})
    scipy.io.wavfile.write(f"{output_name}.wav", rate=music["sampling_rate"], data=music["audio"])

    return None

if __name__ == "__main__":
    for file in TRANSCRIPTION_FILE_LIST:
        with open(file, "r") as f:
            transcription = f.read()
        description = generate_music_description(transcription)
        description_to_audio(description, "output")